import { bi, type Bi } from '../content';
import type { Answers } from '../schema';
import { diversity, percent } from '../scoring';
export type Figure = { id:string; name:string; intro:Bi; idea:Bi; learn:Bi; limit:Bi; sourceTitle:string; url:string; checked:string };
export const FIGURES:Figure[] = [
  {id:'buffett',name:'Warren Buffett',intro:bi('伯克希爾的長期投資者。','A long-term investor at Berkshire Hathaway.'),idea:bi('2023年股東信以長期持有優質企業說明耐心的重要。','His 2023 shareholder letter explains the value of patience in holding outstanding businesses.'),learn:bi('先問等待的理由，而非只問要等多久。','Ask why you would wait, as well as how long.'),limit:bi('等虛擬金幣與評估企業不同；長期持有也可虧損。','Waiting for virtual coins differs from assessing businesses. Long holdings can still lose money.'),sourceTitle:'Berkshire Hathaway 2023 shareholder letter, p. 7',url:'https://www.berkshirehathaway.com/letters/2023ltr.pdf',checked:'2026-09-18'},
  {id:'bogle',name:'John C. Bogle',intro:bi('Vanguard創辦人，推廣低成本投資。','Vanguard founder and advocate of low-cost investing.'),idea:bi('重視廣泛持有市場及控制長期投資成本。','He emphasised broad market ownership and controlling long-term investment costs.'),learn:bi('比較選項時，列出看得見及持續發生的費用。','List upfront and ongoing costs when comparing choices.'),limit:bi('低成本及分散並不保證回報。','Low costs and diversification do not guarantee returns.'),sourceTitle:'Vanguard: 50 years. 50 facts. Indexing since 1976.',url:'https://corporate.vanguard.com/content/corporatesite/us/en/corp/articles/50-years-50-facts-indexing-since-1976.html',checked:'2026-09-18'},
  {id:'markowitz',name:'Harry Markowitz',intro:bi('研究投資組合的經濟學家，1990年諾貝爾經濟學獎得主。','Portfolio economist and 1990 economic sciences laureate.'),idea:bi('評估整個組合的風險與回報，留意資產如何一起變動。','Consider a portfolio’s risk and return, including how its assets move together.'),learn:bi('不要只數籃子數量，也問它們是否面對同一風險。','Ask whether baskets share the same risks, not just how many there are.'),limit:bi('三間虛擬小店並非完整的真實投資組合。','Three fictional shops are not a complete real-world portfolio.'),sourceTitle:'Nobel Prize: The Prize in Economics 1990, press release',url:'https://www.nobelprize.org/prizes/economic-sciences/1990/press-release/',checked:'2026-09-18'},
  {id:'marks',name:'Howard Marks',intro:bi('Oaktree聯合創辦人，撰寫投資備忘錄。','Oaktree co-founder and author of investment memos.'),idea:bi('《Risk Revisited》區分短期波動與永久損失，並強調多種可能結果。','Risk Revisited distinguishes fluctuations from permanent loss and considers a range of possible outcomes.'),learn:bi('先描述可能的損失，再比較為安心付出的成本。','Describe possible losses before comparing the price of reassurance.'),limit:bi('買遊戲保障不能證明真實投資的風險管理能力。','Buying game protection does not establish real investment risk-management ability.'),sourceTitle:'Howard Marks: Risk Revisited (2014), pp. 1–3',url:'https://www.oaktreecapital.com/insights/memo/risk-revisited',checked:'2026-09-18'},
  {id:'lynch',name:'Peter Lynch',intro:bi('曾管理Fidelity Magellan基金的投資者。','Investor and former Fidelity Magellan fund manager.'),idea:bi('買入前要理解企業的故事，並查看財務資料。','Understand a business and examine its financial information before investing.'),learn:bi('用自己的話解釋項目如何運作及資料由誰提供。','Explain how a project works and who supplies the evidence in your own words.'),limit:bi('翻過線索不等於已完成深入研究。','Revealing clues is not the same as thorough research.'),sourceTitle:'Fidelity: Investing legends transcript, p. 3',url:'https://www.fidelity.com/bin-public/060_www_fidelity_com/documents/learning-center/Transcript_Investing%20legends_v2.pdf',checked:'2026-09-18'},
  {id:'kahneman',name:'Daniel Kahneman',intro:bi('研究不確定情境決策的心理學家，2002年諾貝爾經濟學獎得主。','Psychologist studying decisions under uncertainty and 2002 economic sciences laureate.'),idea:bi('等價結果的不同表述可影響選擇。','Different descriptions of equivalent outcomes can influence choices.'),learn:bi('把「保留」與「失去」都換算成最後剩下多少。','Translate both “keep” and “lose” into final amounts.'),limit:bi('兩次回答不能診斷穩定偏誤或人格。','Two answers cannot diagnose a stable bias or personality.'),sourceTitle:'Daniel Kahneman: Nobel lecture, framing effects',url:'https://www.nobelprize.org/uploads/2018/06/kahnemann-lecture.pdf',checked:'2026-09-18'},
];
export type FigureMatch = {figure:Figure; reason:Bi; matched:boolean};
export function matchFigures(a:Answers):FigureMatch[] {
  const candidates:{id:string;strength:number;reason:Bi}[]=[];
  if(a['4']&&percent(a['4'].wait)>=200/3) candidates.push({id:'buffett',strength:percent(a['4'].wait),reason:bi(`第4關：你有${a['4'].wait.filter(Boolean).length}次選擇等待。`,`Game 4: you chose to wait ${a['4'].wait.filter(Boolean).length} times.`)});
  if(a['10']?.clues.includes(1)) candidates.push({id:'bogle',strength:85,reason:bi('第10關：你查看了成本線索。','Game 10: you opened the cost clue.')});
  if(a['5']&&diversity(a['5'].baskets)>=60) candidates.push({id:'markowitz',strength:diversity(a['5'].baskets),reason:bi(`第5關：你的配置為${a['5'].baskets.join('／')}。`,`Game 5: your allocation was ${a['5'].baskets.join(' / ')}.`)});
  if(a['7']?.protect.some(Boolean)) candidates.push({id:'marks',strength:70,reason:bi(`第7關：你在${a['7'].protect.filter(Boolean).length}種價格下選擇保障。`,`Game 7: you chose protection at ${a['7'].protect.filter(Boolean).length} price points.`)});
  if(a['10']&&a['10'].clues.length>=2) candidates.push({id:'lynch',strength:a['10'].clues.length/3*100,reason:bi(`第10關：你查看了${a['10'].clues.length}張線索。`,`Game 10: you opened ${a['10'].clues.length} clues.`)});
  if(a['11']&&a['11'].keep!==a['11'].lose) candidates.push({id:'kahneman',strength:90,reason:bi('第11關：你在兩種措辭下選擇不同。','Game 11: your choices differed between the two wordings.')});
  candidates.sort((x,y)=>y.strength-x.strength||FIGURES.findIndex(f=>f.id===x.id)-FIGURES.findIndex(f=>f.id===y.id));
  const matches:FigureMatch[]=candidates.slice(0,2).map(c=>({figure:FIGURES.find(f=>f.id===c.id)!,reason:c.reason,matched:true}));
  for(const f of FIGURES) if(matches.length<2&&!matches.some(m=>m.figure.id===f.id)) matches.push({figure:f,reason:bi('未有足夠相應選擇；這是一個值得比較的觀點。','There is not enough corresponding evidence. This is an idea to compare.'),matched:false});
  return matches;
}
