import { bi } from '../../shared/content';
export const UI = {
  start:bi('開始探索','Begin exploring'), how:bi('你的選擇，你的航程。','Your choices. Your journey.'),
  lead:bi('用12個小遊戲，發現你如何面對機會、等待與不確定。','Discover how you approach opportunity, waiting and uncertainty through 12 small games.'),
  time:bi('預留約8–12分鐘','Allow around 8–12 minutes'), noLogin:bi('不用登入','No sign-in'), report:bi('專屬雙語報告','Your bilingual report'),
  virtual:bi('所有金幣均為虛擬道具，不能充值、兌換或提現。','All coins are virtual. They cannot be purchased, exchanged or withdrawn.'),
  privacy:bi('答案只留在此瀏覽器分頁。申請電郵寄送時才傳送報告資料；本應用不設參與者資料庫或營銷追蹤。託管及郵件服務商可能處理連線及寄送紀錄。','Answers stay in this browser tab. Report data is sent only when you request email delivery. This app has no participant database or marketing tracking. Hosting and email providers may process connection and delivery records.'),
  introTitle:bi('準備好，便可以出發。','Set off when you are ready.'),
  instructions:bi('閱讀每關的機會與後果，按你當下的想法選擇。沒有標準風險類型，沒有計時壓力，也不按運氣計分。','Read the chances and consequences, then choose what feels right today. There is no ideal risk type, no time pressure, and luck is not scored.'),
  skipNote:bi('可跳過任何一關。第1、3、6、9關全完成才有整體類型；其餘觀察獨立呈現。','You may skip any game. Games 1, 3, 6 and 9 are required for an overall type; other observations remain separate.'),
  role:bi('你今天以甚麼身份來探索？（可選）','Who are you exploring as today? (Optional)'),
  roles:[bi('學生','Student'),bi('家長','Parent'),bi('其他','Other'),bi('略過','Prefer not to say')],
  roleNote:bi('只用作稱呼，不進入計分。','Used for your welcome only, never for scoring.'),
  welcome:[bi('同學，按你的想法探索。','Explore in your own way, student.'),bi('家長，歡迎一起探索。','Parents are welcome to explore too.'),bi('歡迎探索不同選擇。','Welcome to exploring different choices.')],
  continue:bi('繼續航程','Continue the journey'), nextRound:bi('下一小輪','Next round'), skip:bi('跳過本關','Skip this game'), confirm:bi('確認選擇','Confirm my choice'),
  next:bi('下一關','Next game'), results:bi('查看我的報告','See my report'), again:bi('重新開始','Start again'), nextPerson:bi('下一位參與者','Next participant'), redo:bi('重做本關','Try this game again'),
  home:bi('回到起點','Back to the start'), expedition:bi('探索航線','Your expedition'), completed:bi('選擇已記錄','Choice recorded'), choicesOnly:bi('我們記錄選擇，不以運氣評分。','We record choices. Luck does not determine your score.'),
  certain:bi('確定收取','Receive for certain'), chance:bi('選擇機會錢包','Choose the chance wallet'), coin:bi('枚虛擬金幣','virtual coins'), half:bi('◐ 各有一半機會 · 50%','◐ 50% chance of each outcome'),
  round:(n:number,total:number)=>bi(`小輪 ${n}／${total}`,`Round ${n} of ${total}`),
  outcome:(n:number)=>bi(`這次揭曉：${n}枚金幣。選擇已鎖定。`,`This reveal: ${n} coins. Your choice is locked.`),
  pump:bi('充氣 +5','Pump +5'), collect:bi('收集並結束本輪','Collect and finish this round'),
  burst:bi('氣球爆破；本輪未收集金幣歸零。','The balloon burst. This round’s uncollected coins are lost.'),
  banked:(n:number)=>bi(`本輪收集${n}枚。`,`Collected ${n} coins this round.`),
  limit:bi('已達6次上限，系統自動收集。','Six-pump limit reached; coins collected automatically.'),
  probability:(p:number)=>bi(`下一次爆破機會 ${p}%`,`Next-pump burst chance ${p}%`),
  unbanked:bi('本輪未收集','Uncollected this round'), table:bi('查看完整概率及收益表','View the full probability and reward table'),
  pumpNo:bi('充氣次數','Pump'), burstChance:bi('爆破機會','Burst chance'), safeGain:bi('成功後累積','Total after success'),
  keep:bi('確定保留口袋','Keep pocket'), opportunity:bi('機會口袋','Chance pocket'), allocate:bi('放入機會口袋的金幣','Coins in the chance pocket'),
  preview:bi('兩種最終結果預覽','Preview both final outcomes'),
  today:bi('即日取得10枚','10 coins today'), later:(d:number,n:number)=>bi(`模擬${d}日後取得${n}枚`,`${n} coins after ${d} simulated days`),
  simulated:bi('只是模擬；不用真的等待，也沒有真實付款。','A simulation only: no real wait and no real payment.'),
  available:(n:number)=>bi(`尚有${n}枚待分配`,`${n} tokens left to allocate`), equal:bi('平均分配4／4／4','Split equally: 4 / 4 / 4'), reset:bi('清空分配','Clear allocation'),
  shop:(c:string)=>bi(`小店${c}`,`Shop ${c}`), plus:bi('加一枚','Add one'), minus:bi('減一枚','Remove one'),
  selectRange:bi('選擇能安心接受的範圍','Choose a range you feel comfortable with'),
  protection:bi('買盾牌消除風險','Buy a shield to remove the risk'), noProtection:bi('保留金幣並承擔風險','Keep the coins and accept the risk'),
  pack:bi('背包有100枚金幣；25%機會剩60，75%機會剩100。','Your backpack has 100 coins: a 25% chance of 60 remaining, and a 75% chance of 100 remaining.'),
  shield:(n:number)=>bi(`付${n}枚：確定剩${100-n}枚`,`Pay ${n}: ${100-n} remain for certain`),
  yes:bi('是','Yes'), no:bi('否','No'), confidence:bi('你有幾分把握？','How confident are you?'), reveal:bi('鎖定並揭曉','Lock and reveal'),
  correct:(n:number,truth:boolean)=>bi(`本輪答案：${truth?'是':'否'}。你揭曉前的把握是${n}%。`,`Answer: ${truth?'yes':'no'}. Your confidence before the reveal was ${n}%.`),
  route:(c:string)=>bi(`航線${c}`,`Route ${c}`), sail:bi('鎖定航線並啟航','Lock route and set sail'),
  hype:bi('「大家都在談星光小島！」這則虛構消息沒有提供確定的回報。','“Everyone is talking about Starlight Island!” This fictional claim offers no certain return.'),
  join:bi('參與虛構項目','Join the fictional project'), investigate:bi('先再查證','Investigate further'), decline:bi('不參與','Decline'),
  framedKeep:bi('你有60枚：選擇保留20枚，或1/3機會保留60枚、2/3機會保留0枚。','You have 60 coins: keep 20, or a 1/3 chance of keeping 60 and a 2/3 chance of keeping 0.'),
  framedLose:bi('你有60枚：選擇失去40枚，或1/3機會失去0枚、2/3機會失去60枚。','You have 60 coins: lose 40, or a 1/3 chance of losing 0 and a 2/3 chance of losing 60.'),
  sureKeep:bi('確定保留20枚','Keep 20 for certain'), chanceKeep:bi('1/3保留60；2/3保留0','1/3 keep 60; 2/3 keep 0'),
  sureLose:bi('確定失去40枚','Lose 40 for certain'), chanceLose:bi('1/3失去0；2/3失去60','1/3 lose 0; 2/3 lose 60'),
  thirds:bi('1/3約33.3%；2/3約66.7%。','1/3 is about 33.3%; 2/3 is about 66.7%.'),
  fixed:bi('固定需要','Fixed needs'), activities:bi('活動','Activities'), buffer:bi('備用','Buffer'), budget:bi('為備用預留金幣','Reserve coins as a buffer'),
  surprise:bi('鎖定預算，看看意外支出','Lock budget and reveal the surprise expense'),
  reportTitle:bi('你的金融探索報告','Your finance discovery report'), reportIntro:bi('12個小選擇，開啟理解自己的新角度。','Small choices, new ways to understand yourself.'),
  incomplete:bi('探索尚未完成','Your exploration is incomplete'), missing:bi('完成以下核心關卡，才可顯示整體類型。其他已完成觀察仍會保留。','Complete these core games to see your overall type. Your other observations are preserved.'),
  tendency:bi('本次風險選擇傾向','Risk-taking tendency in this activity'), scale:bi('0 偏向確定結果 · 100 接受更多不確定性','0 Favour certainty · 100 Accept more uncertainty'),
  indexNote:bi('四個核心指標等權平均。不是百分位、準確率或勝率；五類為本活動預設分組。','An equal average of four core indicators. Not a percentile, accuracy or win rate; the five groups are defined for this activity.'),
  observations:bi('六個觀察，六個角度','Six observations, six perspectives'), observationNote:bi('這些是任務內的描述性指標，不是經驗證的心理維度，也不是越高越優秀。','These describe choices within the tasks. They are not validated psychological dimensions, and higher is not better.'),
  evidence:bi('沿途的選擇','Choices along the way'), tips:bi('把發現帶進日常','Take your discoveries further'),
  figures:bi('你的選擇，與哪些金融觀點有共鳴？','Which financial ideas echo your choices?'), editorial:bi('選擇對照（本專案的解釋）','Choice connection (our editorial interpretation)'), compare:bi('值得比較的觀點','Ideas to compare'), source:bi('資料來源','Source'), learn:bi('可學的思路','An idea to learn from'), limitation:bi('留意局限','Keep the limits in mind'),
  exploreTitle:bi('把好奇心變成金融知識','Turn curiosity into financial understanding.'), exploreText:bi('遊戲涉及理解風險、比較選擇、運用資料及規劃資源。金融學習讓你進一步探索這些問題。','These games involve understanding risk, comparing choices, using information and planning resources. Studying finance lets you explore these questions further.'),
  department:bi('認識金融系','Explore the Department of Finance'), apply:bi('了解課程及報名','Explore programmes and apply'), finance:bi('金融學課程','Finance programme'), information:bi('金融及資訊管理課程','Finance and Information Management programme'),
  download:bi('下載雙語PDF','Download bilingual PDF'), email:bi('以電郵接收報告','Email my report'), emailLabel:bi('電郵地址','Email address'),
  consent:bi('我主動申請寄送此報告，並同意為寄送處理我的電郵地址及本次測試資料。不會加入招生郵件名單。','I request this report and agree to the processing of my email address and activity data for delivery. I will not be added to an admissions mailing list.'),
  send:bi('申請寄送PDF','Request my PDF by email'), unavailable:bi('電郵服務暫未啟用，請先下載PDF。','Email delivery is not available yet. Please download your PDF.'),
  generating:bi('正在製作雙語PDF…','Preparing your bilingual PDF…'), sending:bi('正在提交寄送…','Submitting your email request…'), accepted:bi('服務商已接受寄送，請稍後查看收件匣及垃圾郵件匣。這不代表已確認送達。','The provider has accepted your request. Please check your inbox and junk folder shortly. Delivery has not been confirmed.'),
  rate:bi('寄送申請過於頻繁或今日額度已滿。請稍後再試，或先下載PDF。','Requests are too frequent or today’s allowance is full. Try later, or download your PDF.'),
  failed:bi('未能完成，請重試。你的結果仍在，可先下載PDF。','This could not be completed. Please retry. Your results remain available for PDF download.'), invalid:bi('請輸入一個有效電郵地址、確認寄送同意，並完成人機驗證。','Enter one valid email address, confirm delivery consent and complete the verification.'),
  verify:bi('請完成人機驗證；過期後請重新驗證。','Complete verification; repeat it if it expires.'), retryVerify:bi('重新載入驗證','Reload verification'),
  varied:bi('你在不同情境下作出了不同選擇。','You made different choices across scenarios.'),
  recovery:bi('已恢復本分頁的探索進度。','Your progress in this tab has been restored.'),
  storageError:bi('瀏覽器未能儲存進度；重新整理會失去本輪答案。','Your browser cannot save progress; refreshing will lose these answers.'),
  saved:bi('PDF已準備下載。','Your PDF is ready to download.'), noData:bi('尚未有觀察','No observation yet'),
};
